### PR TITLE
handle the case that the full filepath is provided

### PR DESCRIPTION
**Pull request by asiandrummer**
`includesFile` may be provided of a file path that already includes the config directory as the part of the file path. The proposed changes check if it already does so before joining the config directory and the file path together.

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
LGTM 👍 

@schickling will you merge it and publish a new version?

**Comment by schickling** [comment]
Thanks a lot! Can you still resolve the file conflict? I've just merged #33

**Comment by asiandrummer** [comment]
@schickling it seems like, since I don't have the write access, resolving the merge conflict is a little bit annoying and I have to recreate another PR to do this :( would it be okay for me to be added as a contributor to this repo please?

**Comment by schickling** [comment]
Thanks a lot! (Just added you as a maintainer.)

**Comment by asiandrummer** [comment]
Thanks so much @schickling - if we could release another patch with this included that'd be much appreciated ;) I guess I could do that, but wanted to get your blessing first.

**Comment by asiandrummer** [comment]
Thanks so much!!

**Pull request merged**
